### ISSUE TITLE
slightly simplify the example

### ISSUE THREAD

**Issue by capaj** [mweststrate/use-immer#1]
the example could be simplified:
https://codesandbox.io/s/0yyomw1l4p

but maybe it's just my personal preference. Feel free to just ignore and close this.

**Comment by wheelo** [comment]
nice example

**Comment by mweststrate** [comment]
Thanks for the suggestion :-). it is what I would probably do as well in practice in this specific case, but if the event handlers are slightly bigger, then extracting a separate function is the more maintainable approach I think, and hence the best practice.
