### ISSUE TITLE
alternate syntax for reducer

### ISSUE THREAD

**Issue by xaviergonz** [mweststrate/use-immer#2]
what about something like this instead? 
```js
function reducer(draft, action, setState) {
  switch (action.type) {
    case "reset":
      setState( initialstate) ;
      break
    case "increment":
      draft.count++;
      break
    case "decrement":
      draft.count--;
      break
  }
}```

**Comment by xaviergonz** [comment]
and if it returns something it throws (or does nothing)

**Comment by mweststrate** [comment]
I think it in it's current form, it would make this approach slightly different from how normal immer producers look, making it confusing. 

That being said, this proposal is quite similar to https://github.com/mweststrate/immer/issues/246, which introduces a `replace` api, and I think we can continue the discussion there :)
